[package]
name = "pyext-example"
version = "0.1.0"
authors = ["fx_kirin"]

[lib]
name = "rust_ext"
crate-type = ["cdylib"]

[dependencies]
numpy = "0.15.1"
ndarray = "0.12"
pyo3 = { version = "0.15", features = ["extension-module"] }
